// Code generated by hero.
// source: /home/doublen/workspace/go/src/github.com/doublen987/Projects/MySite/server/webportal/template/homepage/edithomepage.html
// DO NOT EDIT!
package template

import (
	"io"

	"github.com/doublen987/Projects/MySite/server/persistence/models"
	"github.com/shiyanhui/hero"
)

func HandleEditHomePage(header string, sections []models.PageSection, tags []models.Tag, w io.Writer) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>doublen987</title>
    <link rel="icon" href="/content/doublen987-logo-5.svg">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bangers&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@500;600&family=Voces&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/content/shared.css">
    <link rel="stylesheet" href="/content/homepage.css">
    <link rel="stylesheet" href="/content/projects.css">
    <link rel="stylesheet" href="/content/blog.css">
    <link rel="stylesheet" href="/content/login.css">
    <link rel="stylesheet" href="/content/post.css">
    <link rel="stylesheet" href="/content/editor.css">
    <link rel="stylesheet" href="/content/knowledge-timeline.css">
    <link rel="stylesheet" href="/content/edithomepage.css">
    <link rel="stylesheet" href="/content/dashboard.css">
    <script src="/content/js/nav.js"></script>
</head>
<body>
    <div></div>
    <div></div>
    <header class="main-header">
        <div>
            <!-- <button class="toggle-button">
                <span class="toggle-button__bar"></span>
                <span class="toggle-button__bar"></span>
                <span class="toggle-button__bar"></span>
            </button>
            <a href="index.html" class="main-header__brand">
                <img src="images/uhost-icon.png" alt="uHost - Your favorite hosting company">
            </a> -->
        </div>
        <nav class="main-nav">
            <div class="nav-icon-container nav-icon-container-not-clicked">
                <img class="nav-icon" src="/content/doublen987-logo-5.svg" />
            </div>
            <ul class="nav-items">
                <li class="nav-item">
                    <a href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a href="/blog/">Blog</a>
                </li>
                <li class="nav-item">
                    <a href="/projects/">Projects</a>
                </li>
                <li class="nav-item nav-item-left">
                    <a href="https://github.com/doublen987" target="_blank">
                    <svg id="github-link" xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
                    </a>
                </li>
                <li class="nav-item nav-item-left">
                    <a href="https://www.linkedin.com/in/nikola-nesovic-24214219a/" target="_blank">
                    <svg id="linkedin-link" xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 24 24"><path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"/></svg>
                    </a>
                </li>
                <li class="nav-item nav-item-left">
                    <a href="mailto:doublen987@gmail.com" target="_blank">
                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 24 24"><path d="M12.042 23.648c-7.813 0-12.042-4.876-12.042-11.171 0-6.727 4.762-12.125 13.276-12.125 6.214 0 10.724 4.038 10.724 9.601 0 8.712-10.33 11.012-9.812 6.042-.71 1.108-1.854 2.354-4.053 2.354-2.516 0-4.08-1.842-4.08-4.807 0-4.444 2.921-8.199 6.379-8.199 1.659 0 2.8.876 3.277 2.221l.464-1.632h2.338c-.244.832-2.321 8.527-2.321 8.527-.648 2.666 1.35 2.713 3.122 1.297 3.329-2.58 3.501-9.327-.998-12.141-4.821-2.891-15.795-1.102-15.795 8.693 0 5.611 3.95 9.381 9.829 9.381 3.436 0 5.542-.93 7.295-1.948l1.177 1.698c-1.711.966-4.461 2.209-8.78 2.209zm-2.344-14.305c-.715 1.34-1.177 3.076-1.177 4.424 0 3.61 3.522 3.633 5.252.239.712-1.394 1.171-3.171 1.171-4.529 0-2.917-3.495-3.434-5.246-.134z"/></svg>
                    </a>
                </li>
            </ul>
            <div id="modal" class="modal-hidden">
                <div class="modal-nav-item">
                    <a href="/">Home</a>
                </div>
                <div class="modal-nav-item">
                    <a href="/blog/">Blog</a>
                </div>
                <div class="modal-nav-item">
                    <a href="/projects/">Projects</a>
                </div>
                <div class="modal-nav-item">
                    <div class="modal-social">
                        <a href="https://github.com/doublen987" target="_blank">
                        <svg id="github-link" xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
                    </a>
                    </div>
                    <div class="modal-social">
                        <a href="https://www.linkedin.com/in/nikola-nesovic-24214219a/" target="_blank">
                        <svg id="linkedin-link" xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 24 24"><path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"/></svg>
                    </a>
                    </div>
                    <div class="modal-social">
                        <a href="mailto:doublen987@gmail.com" target="_blank">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 24 24"><path d="M12.042 23.648c-7.813 0-12.042-4.876-12.042-11.171 0-6.727 4.762-12.125 13.276-12.125 6.214 0 10.724 4.038 10.724 9.601 0 8.712-10.33 11.012-9.812 6.042-.71 1.108-1.854 2.354-4.053 2.354-2.516 0-4.08-1.842-4.08-4.807 0-4.444 2.921-8.199 6.379-8.199 1.659 0 2.8.876 3.277 2.221l.464-1.632h2.338c-.244.832-2.321 8.527-2.321 8.527-.648 2.666 1.35 2.713 3.122 1.297 3.329-2.58 3.501-9.327-.998-12.141-4.821-2.891-15.795-1.102-15.795 8.693 0 5.611 3.95 9.381 9.829 9.381 3.436 0 5.542-.93 7.295-1.948l1.177 1.698c-1.711.966-4.461 2.209-8.78 2.209zm-2.344-14.305c-.715 1.34-1.177 3.076-1.177 4.424 0 3.61 3.522 3.633 5.252.239.712-1.394 1.171-3.171 1.171-4.529 0-2.917-3.495-3.434-5.246-.134z"/></svg>
                    </a>
                    </div>
                </div>
                
            </div>
        </nav>
    </header>
    <main>
        `)
	_buffer.WriteString(`
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="/content/js/he.js"></script>
    <script src="/content/js/edithomepage.js"></script>

    <div class="editor-container">
        <div class="sections-header">Sections:</div>
        <form onsubmit="event.preventDefault()" id="form1" action="/homepage/edit" enctype="multipart/form-data" method="POST">
            `)
	for _, section := range sections {
		_buffer.WriteString(`
            <div class="input-container" id="input-container-`)
		hero.EscapeHTML(section.GetID(), _buffer)
		_buffer.WriteString(`">
                `)
		if as, ok := section.(models.TextSection); section.GetType() == "text" && ok {

			_buffer.WriteString(`<div class="homepage-section-editor" id="homepage-section-editor-`)
			hero.EscapeHTML(as.ID, _buffer)
			_buffer.WriteString(`">
    <div class="homepage-section-input-container-x">
        <svg width="20" height="20" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><!--! Font Awesome Pro 6.2.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M376.6 84.5c11.3-13.6 9.5-33.8-4.1-45.1s-33.8-9.5-45.1 4.1L192 206 56.6 43.5C45.3 29.9 25.1 28.1 11.5 39.4S-3.9 70.9 7.4 84.5L150.3 256 7.4 427.5c-11.3 13.6-9.5 33.8 4.1 45.1s33.8 9.5 45.1-4.1L192 306 327.4 468.5c11.3 13.6 31.5 15.4 45.1 4.1s15.4-31.5 4.1-45.1L233.7 256 376.6 84.5z"/></svg>
    </div>
    <div>
        <label for="post-title" class="editor-label">Header: </label>
        <input name="Header" id="section-header-input-`)
			hero.EscapeHTML(as.ID, _buffer)
			_buffer.WriteString(`" class="editor-input"></input>
    </div>
    <div>
        <label for="post-content" class="editor-label">Content: </label>
        <textarea name="Content" id="section-content-input-`)
			hero.EscapeHTML(as.ID, _buffer)
			_buffer.WriteString(`"></textarea>
    </div>
    <div>
        <button class="editor-update-button">Update</button>
    </div>
    
</div>
<div class="homepage-section-preview" id="homepage-section-preview-`)
			hero.EscapeHTML(as.ID, _buffer)
			_buffer.WriteString(`">
    
    <div class="homepage-section-preview-header" id="header-`)
			hero.EscapeHTML(as.ID, _buffer)
			_buffer.WriteString(`">Header: `)
			hero.EscapeHTML(as.Header, _buffer)
			_buffer.WriteString(`</div>
    <div class="homepage-section-preview-content" id="content-`)
			hero.EscapeHTML(as.ID, _buffer)
			_buffer.WriteString(`">Content: `)
			hero.EscapeHTML(as.Content, _buffer)
			_buffer.WriteString(`</div>
    
</div>

`)
		}
		if as, ok := section.(models.ImageSection); section.GetType() == "image" && ok {
			_buffer.WriteString(`<div class="homepage-section-preview" id="homepage-section-preview-`)
			hero.EscapeHTML(as.ID, _buffer)
			_buffer.WriteString(`">
    <img class="homepage-section-image" id="homepage-section-image-`)
			hero.EscapeHTML(as.ID, _buffer)
			_buffer.WriteString(`" src="`)
			hero.EscapeHTML(as.Image, _buffer)
			_buffer.WriteString(`">
</div>
<div class="homepage-section-editor" id="homepage-section-editor-`)
			hero.EscapeHTML(as.ID, _buffer)
			_buffer.WriteString(`">
    <label for="homepage-section-editor-input" class="editor-label">Image: </label>
    <input name="homepage-section-editor-input" type="file" accept="image/*" id="homepage-section-editor-input-`)
			hero.EscapeHTML(as.ID, _buffer)
			_buffer.WriteString(`"></input>
</div>`)
		}
		if as, ok := section.(models.StackSection); section.GetType() == "stack" && ok {
			_buffer.WriteString(`<div id="homepage-section-preview-`)
			hero.EscapeHTML(as.ID, _buffer)
			_buffer.WriteString(`">
    `)
			for _, tag := range as.Tags {
				_buffer.WriteString(`
        <div>
            <div><img src="`)
				hero.EscapeHTML(tag.Thumbnail, _buffer)
				_buffer.WriteString(`" /></div>
            <div>`)
				hero.EscapeHTML(tag.Name, _buffer)
				_buffer.WriteString(`</div>
        </div>
    `)
			}
			_buffer.WriteString(`
</div>
<div  id="homepage-section-editor-`)
			hero.EscapeHTML(as.ID, _buffer)
			_buffer.WriteString(`">

    `)
			for _, tag := range tags {
				_buffer.WriteString(`
        <div>
            <input class="homepage-section-editor-tag-checkbox" type="checkbox"></input>
            <div><img src="`)
				hero.EscapeHTML(tag.Thumbnail, _buffer)
				_buffer.WriteString(`" /></div>
            <div>`)
				hero.EscapeHTML(tag.Name, _buffer)
				_buffer.WriteString(`</div>
        </div>
    `)
			}
			_buffer.WriteString(`
</div>`)
		}
		_buffer.WriteString(`
            </div>
            `)
	}
	_buffer.WriteString(`
            
        </form>
        <button id="show-type-modal-button">Add section</button>
        <button id="save-homepage-sections-button">Save</button>
        <div id="homepage-section-type-modal">
            <button id="type-modal-button-text">Text</button>
            <button id="type-modal-button-image">Image</button>
            <button id="type-modal-button-stack">Stack</button>
        </div>
    </div>
    
`)

	_buffer.WriteString(`
    </main>
    <footer>
        
    </footer>
    <script>
        initMobileMenu();
    </script>
</body>
</html>`)
	w.Write(_buffer.Bytes())

}
