// Code generated by hero.
// source: /home/doublen987/workspace/go/src/github.com/doublen987/Projects/MySite/server/webportal/template/homepage/homepage.html
// DO NOT EDIT!
package template

import (
	"context"
	"fmt"
	"io"

	"github.com/doublen987/Projects/MySite/server/functionality"
	"github.com/doublen987/Projects/MySite/server/persistence/models"
	"github.com/shiyanhui/hero"
)

func Homepage(ctx context.Context, settings models.Settings, page models.Page2, w io.Writer) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>`)
	_buffer.WriteString(settings.WebsiteName)
	_buffer.WriteString(`</title>
    <link rel="icon" href="/content/doublen987-logo-5.svg">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bangers&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@500;600&family=Voces&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/content/shared.css">
    <link rel="stylesheet" href="/content/homepage.css">
    <link rel="stylesheet" href="/content/projects.css">
    <link rel="stylesheet" href="/content/blog.css">
    <link rel="stylesheet" href="/content/login.css">
    <link rel="stylesheet" href="/content/post.css">
    <link rel="stylesheet" href="/content/editor.css">
    <link rel="stylesheet" href="/content/knowledge-timeline.css">
    <link rel="stylesheet" href="/content/edithomepage.css">
    <link rel="stylesheet" href="/content/dashboard.css">
    <link rel="stylesheet" href="/content/tag-list-editor.css">
    <script src="/content/js/nav.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios@1.1.2/dist/axios.min.js"></script>
    <script src="/content/js/modelviewer/stl_viewer.min.js"></script>
    <script src="/content/js/modelviewer.js"></script>
    <style>
        :root {
            --bg-color-1: `)
	_buffer.WriteString(settings.BackgroundColor1)
	_buffer.WriteString(`;
            --bg-color-2: `)
	_buffer.WriteString(settings.BackgroundColor2)
	_buffer.WriteString(`;
            --bg-color-3: `)
	_buffer.WriteString(settings.BackgroundColor3)
	_buffer.WriteString(`;
            --text-color-1: `)
	_buffer.WriteString(settings.TextColor1)
	_buffer.WriteString(`;
            --text-color-2: `)
	_buffer.WriteString(settings.TextColor2)
	_buffer.WriteString(`;
            --text-color-3: `)
	_buffer.WriteString(settings.TextColor3)
	_buffer.WriteString(`;
        }
    </style>
</head>
<body>
    <div></div>
    <header class="headers-container">
        `)

	sessionData, ok := ctx.Value("sessionData").(functionality.SessionData)
	if ok && sessionData.User.Username != "" {

		_buffer.WriteString(`
            <div class="admin-header">
                    <nav class="admin-menu">
                        <ul class="admin-nav-items">
                            <li class="admin-nav-item">
                                <a href="/">Home</a>
                            </li>
                            <li class="admin-nav-item">
                                <a href="/dashboard/">Dashboard</a>
                            </li>
                            <li class="admin-nav-item">
                                <a href="/blog/edit">Posts</a>
                            </li>
                            <li class="admin-nav-item">
                                <a href="/projects/edit">Projects</a>
                            </li>
                            <li class="admin-nav-item">
                                <a href="/tags/edit">Tags</a>
                            </li>
                            <li class="admin-nav-item">
                                <a href="/homepage/edit">Pages</a>
                            </li>
                            <li class="admin-nav-item">
                                <a href="/logout">Logout</a>
                            </li>
                        </ul>
                    </nav>
            </div>
        `)
	}
	_buffer.WriteString(`
        <div class="main-header">
            <div>
                <!-- <button class="toggle-button">
                    <span class="toggle-button__bar"></span>
                    <span class="toggle-button__bar"></span>
                    <span class="toggle-button__bar"></span>
                </button>
                <a href="index.html" class="main-header__brand">
                    <img src="images/uhost-icon.png" alt="uHost - Your favorite hosting company">
                </a> -->
            </div>
            <nav class="main-nav">
                <div class="nav-icon-container nav-icon-container-not-clicked">
                    `)
	if settings.Logo != "" {
		_buffer.WriteString(`
                        <img class="nav-icon" src="/content/images/`)
		_buffer.WriteString(settings.Logo)
		_buffer.WriteString(`" />
                    `)
	} else {
		_buffer.WriteString(`
                        <img class="nav-icon" src="/content/doublen987-logo-5.svg" />
                    `)
	}
	_buffer.WriteString(`
                </div>
                <ul class="nav-items">
                    <li class="nav-item">
                        <a href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="/blog/">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a href="/projects/">Projects</a>
                    </li>
                </ul>
                <ul class="nav-items social-nav">
                    <li class="nav-item nav-item-left">
                        <a href="https://github.com/doublen987" target="_blank">
                        <svg id="github-link" xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
                        </a>
                    </li>
                    <li class="nav-item nav-item-left">
                        <a href="https://www.linkedin.com/in/nikola-nesovic-24214219a/" target="_blank">
                        <svg id="linkedin-link" xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 24 24"><path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"/></svg>
                        </a>
                    </li>
                    <li class="nav-item nav-item-left">
                        <a href="mailto:doublen987@gmail.com" target="_blank">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 24 24"><path d="M12.042 23.648c-7.813 0-12.042-4.876-12.042-11.171 0-6.727 4.762-12.125 13.276-12.125 6.214 0 10.724 4.038 10.724 9.601 0 8.712-10.33 11.012-9.812 6.042-.71 1.108-1.854 2.354-4.053 2.354-2.516 0-4.08-1.842-4.08-4.807 0-4.444 2.921-8.199 6.379-8.199 1.659 0 2.8.876 3.277 2.221l.464-1.632h2.338c-.244.832-2.321 8.527-2.321 8.527-.648 2.666 1.35 2.713 3.122 1.297 3.329-2.58 3.501-9.327-.998-12.141-4.821-2.891-15.795-1.102-15.795 8.693 0 5.611 3.95 9.381 9.829 9.381 3.436 0 5.542-.93 7.295-1.948l1.177 1.698c-1.711.966-4.461 2.209-8.78 2.209zm-2.344-14.305c-.715 1.34-1.177 3.076-1.177 4.424 0 3.61 3.522 3.633 5.252.239.712-1.394 1.171-3.171 1.171-4.529 0-2.917-3.495-3.434-5.246-.134z"/></svg>
                        </a>
                    </li>
                </ul>
                
                
                
            </nav>
        </div>
        <div id="modal" class="modal-hidden">
            <div class="modal-nav-item">
                <a href="/">Home</a>
            </div>
            <div class="modal-nav-item">
                <a href="/blog/">Blog</a>
            </div>
            <div class="modal-nav-item">
                <a href="/projects/">Projects</a>
            </div>
            <div class="modal-nav-item">
                <div class="modal-social">
                    <a href="https://github.com/doublen987" target="_blank">
                    <svg id="github-link" xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
                </a>
                </div>
                <div class="modal-social">
                    <a href="https://www.linkedin.com/in/nikola-nesovic-24214219a/" target="_blank">
                    <svg id="linkedin-link" xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 24 24"><path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"/></svg>
                </a>
                </div>
                <div class="modal-social">
                    <a href="mailto:doublen987@gmail.com" target="_blank">
                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 24 24"><path d="M12.042 23.648c-7.813 0-12.042-4.876-12.042-11.171 0-6.727 4.762-12.125 13.276-12.125 6.214 0 10.724 4.038 10.724 9.601 0 8.712-10.33 11.012-9.812 6.042-.71 1.108-1.854 2.354-4.053 2.354-2.516 0-4.08-1.842-4.08-4.807 0-4.444 2.921-8.199 6.379-8.199 1.659 0 2.8.876 3.277 2.221l.464-1.632h2.338c-.244.832-2.321 8.527-2.321 8.527-.648 2.666 1.35 2.713 3.122 1.297 3.329-2.58 3.501-9.327-.998-12.141-4.821-2.891-15.795-1.102-15.795 8.693 0 5.611 3.95 9.381 9.829 9.381 3.436 0 5.542-.93 7.295-1.948l1.177 1.698c-1.711.966-4.461 2.209-8.78 2.209zm-2.344-14.305c-.715 1.34-1.177 3.076-1.177 4.424 0 3.61 3.522 3.633 5.252.239.712-1.394 1.171-3.171 1.171-4.529 0-2.917-3.495-3.434-5.246-.134z"/></svg>
                </a>
                </div>
            </div>
        </div>
    </header>
    <main>
        `)
	_buffer.WriteString(`
    <div class="homepage-container">
        `)
	for index, section := range page.Sections {

		sectionType := section.GetType()
		if sectionType == "text" {
			textSection, _ := section.(models.TextSection)
			header := textSection.Header
			content := textSection.Content
			if true {

				_buffer.WriteString(`
                <div class="page-section text-section">
                    <h3 class="homepage-heading">`)
				_buffer.WriteString(header)
				_buffer.WriteString(`</h3>
                    
                    <div class="homepage-content">`)
				_buffer.WriteString(content)
				_buffer.WriteString(`</div>
                </div>
            `)
			}
		}

		if sectionType == "stack" {
			stackSection, _ := section.(models.StackSection)
			name := stackSection.Name
			tagSections := stackSection.TagSections

			_buffer.WriteString(`
                <div class="page-section stack-section">
                    <h3 class="homepage-heading">`)
			hero.EscapeHTML(name, _buffer)
			_buffer.WriteString(`</h3>
                    `)

			for _, tagSection := range tagSections {
				name := tagSection.Name

				_buffer.WriteString(`
                    <div class="homepage-stack">
                        <div class="icon-container-label" >`)
				hero.EscapeHTML(name, _buffer)
				_buffer.WriteString(`</div>
                        <div class="icon-list">
                            `)

				tags := tagSection.Tags
				for _, tag := range tags {

					_buffer.WriteString(`
                                <div class="icon-container">
                                    <img src="/content/images/`)
					hero.EscapeHTML(tag.Thumbnail, _buffer)
					_buffer.WriteString(`" class="tech-icon"/>
                                </div>
                            `)

				}

				_buffer.WriteString(`
                        </div>
                    </div>
                    `)
			}
			_buffer.WriteString(`
                </div>
            `)
		}

		if sectionType == "image" {
			imageSection, _ := section.(models.ImageSection)
			fmt.Println(section)

			_buffer.WriteString(`
                <div class="page-section image-section" style="text-align: `)
			hero.EscapeHTML(imageSection.Align, _buffer)
			_buffer.WriteString(`;">
                    <img src="/content/images/`)
			hero.EscapeHTML(imageSection.Image, _buffer)
			_buffer.WriteString(`" class="image-section-image" width="`)
			hero.FormatFloat(float64(imageSection.Width), _buffer)
			_buffer.WriteString(`" height="`)
			hero.FormatFloat(float64(imageSection.Height), _buffer)
			_buffer.WriteString(`"/>
                </div>
            `)
		}

		if sectionType == "3dmodel" {
			modelSection, _ := section.(models.ModelSection)
			filename := modelSection.FileName

			_buffer.WriteString(`
                <div class="page-section model-section">
                    <div class="section-model" id="section-model-`)
			hero.FormatInt(int64(index), _buffer)
			_buffer.WriteString(`"></div>
                   <div class="model-filename" style="display: none;">`)
			hero.EscapeHTML(filename, _buffer)
			_buffer.WriteString(`</div>
                </div>
            `)
		}
	}
	_buffer.WriteString(`
        <!-- <div class="page-section">
            
        </div>
        <div class="page-section">
            <h3 class="homepage-heading">About Me</h3>
            
            <p class="homepage-content">I'm currently a college student at the University of Belgrade looking for work in 
                the web development industry. <br> My programming journey started 10 years ago. Since 
                then I finished high school at Belgrade's 14th gimnasium, enrolled at University of Belgrade's Faculty of 
                Organisational Science's IT programme, and used all sorts of databases, languages and frameworks.</p>
        </div>
        <div class="page-section">
            <h3 class="homepage-heading">Qualifications</h3>
            <ul>
                <li class="homepage-qualifications">High school degree from Belgrade's 14th gimnasium</li>
                <li class="homepage-qualifications">3rd year of a 4 year bachelor's degree at the University of Belgrade</li>
                <li class="homepage-qualifications">Can speak English and Serbian fluently</li>
            </ul>
        </div>
        <div class="page-section">
            <h3 class="homepage-heading">My Stack</h3>
            <div class="homepage-stack">
                <div class="icon-container-label" >Client Side:</div>
                <div class="icon-list">
                    <div class="icon-container">
                        <img src="/content/images/HTML5-logo.svg" class="tech-icon"/>
                    </div>
                    <div class="icon-container">
                        <img src="/content/images/CSS3-logo.svg" class="tech-icon"/>
                    </div>
                    <div class="icon-container">
                        <img src="/content/images/JavaScript-logo.svg" class="tech-icon"/>
                    </div>
                    <div class="icon-container">
                        <img src="/content/images/React-logo.svg" class="tech-icon"/>
                    </div>
                    <div class="icon-container">
                        <img src="/content/images/Typescript-logo.svg" class="tech-icon"/>
                    </div>
                    <div class="icon-container">
                        <img src="/content/images/PixiJS-logo.svg" class="tech-icon"/>
                    </div>
                    <div class="icon-container">
                        <img src="/content/images/WebGL-logo.svg" class="tech-icon"/>
                    </div>
                    <div class="icon-container">
                        <img src="/content/images/C++-logo.svg" class="tech-icon"/>
                    </div>
                    <div class="icon-container">
                        <img src="/content/images/Webpack-logo.svg" class="tech-icon"/>
                    </div>
                </div>
            </div>
            <div class="homepage-stack">
                <div class="icon-container-label" >Server Side:</div>
                <div class="icon-list">
                    <div class="icon-container">
                        <img src="/content/images/Go-logo.svg" class="tech-icon"/>
                    </div>
                    <div class="icon-container">
                        <img src="/content/images/Docker-logo.svg" class="tech-icon"/>
                    </div>
                    <div class="icon-container">
                        <img src="/content/images/Kubernetes-logo.svg" class="tech-icon"/>
                    </div>
                    <div class="icon-container">
                        <img src="/content/images/NodeJS-logo.svg" class="tech-icon"/>
                    </div>
                    <div class="icon-container">
                        <img src="/content/images/Java-logo.svg" class="tech-icon"/>
                    </div>
                    <div class="icon-container">
                        <img src="/content/images/AWS-logo.svg" class="tech-icon"/>
                    </div>
                    <div class="icon-container">
                        <img src="/content/images/Heroku-logo.svg" class="tech-icon"/>
                    </div>
                </div>
            </div>
            <div class="homepage-stack">
                <div class="icon-container-label">Databases:</div>
                <div  class="icon-list">
                    <div class="icon-container">
                        <img src="/content/images/MongoDB-logo.svg" class="tech-icon"/>
                    </div>
                    <div class="icon-container">
                        <img src="/content/images/Postgresql-logo.svg" class="tech-icon"/>
                    </div>
                    <div class="icon-container">
                        <img src="/content/images/Redis-logo.svg" class="tech-icon"/>
                    </div>
                    <div class="icon-container">
                        <img src="/content/images/MySQL-logo.svg" class="tech-icon"/>
                    </div>
                </div>
            </div>
            <div class="homepage-stack">
                <div class="icon-container-label">Other tools:</div>
                <div class="icon-list">
                    <div class="icon-container">
                        <img src="/content/images/Git-logo.svg" class="tech-icon"/>
                    </div>
                    <div class="icon-container">
                        <img src="/content/images/Vim-logo.svg" class="tech-icon"/>
                    </div>
                    <div class="icon-container">
                        <img src="/content/images/Visual-Studio.svg" class="tech-icon"/>
                    </div>
                </div>
            </div>
        </div> -->
    </div>
    <script>
        window.onload = function() {
            let modelSections = document.getElementsByClassName("model-section")
            for(let i = 0; i < modelSections.length; i++) {
                let fileName = modelSections[i].getElementsByClassName("model-filename")[0].innerHTML
                let sectionModel = modelSections[i].getElementsByClassName("section-model")[0]
                let id = sectionModel.id
                var stl_viewer = init3dViewer(id, {height: "250px"})
                stl_viewer.add_model({id:i, filename: '/content/images/'+fileName})
            }
        }
        
    </script>
`)

	_buffer.WriteString(`
    </main>
    <footer>
        This site or product includes IP2Location LITE data available from <a href="https://lite.ip2location.com">https://lite.ip2location.com</a>.
    </footer>
    <script>
        initMobileMenu();
    </script>
</body>
</html>`)
	w.Write(_buffer.Bytes())

}
