// Code generated by hero.
// source: /home/doublen987/workspace/go/src/github.com/doublen987/Projects/MySite/server/webportal/template/homepage/homepagesections/textsection.html
// DO NOT EDIT!
package template
