// Code generated by hero.
// source: /home/doublen/workspace/go/src/github.com/doublen987/Projects/MySite/server/webportal/template/homepage/homepagesections/imagesection.html
// DO NOT EDIT!
package template
