// Code generated by hero.
// source: /home/doublen/workspace/go/src/github.com/doublen987/Projects/MySite/server/webportal/template/tag/edittag.html
// DO NOT EDIT!
package template

import (
	"io"

	"github.com/doublen987/Projects/MySite/server/persistence/models"
	"github.com/shiyanhui/hero"
)

func HandleEditTag(tags []models.Tag, w io.Writer) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>doublen987</title>
    <link rel="icon" href="/content/doublen987-logo-5.svg">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bangers&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@500;600&family=Voces&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/content/shared.css">
    <link rel="stylesheet" href="/content/homepage.css">
    <link rel="stylesheet" href="/content/projects.css">
    <link rel="stylesheet" href="/content/blog.css">
    <link rel="stylesheet" href="/content/login.css">
    <link rel="stylesheet" href="/content/post.css">
    <link rel="stylesheet" href="/content/editor.css">
    <link rel="stylesheet" href="/content/knowledge-timeline.css">
    <link rel="stylesheet" href="/content/edithomepage.css">
    <link rel="stylesheet" href="/content/dashboard.css">
    <script src="/content/js/nav.js"></script>
</head>
<body>
    <div></div>
    <div></div>
    <header class="main-header">
        <div>
            <!-- <button class="toggle-button">
                <span class="toggle-button__bar"></span>
                <span class="toggle-button__bar"></span>
                <span class="toggle-button__bar"></span>
            </button>
            <a href="index.html" class="main-header__brand">
                <img src="images/uhost-icon.png" alt="uHost - Your favorite hosting company">
            </a> -->
        </div>
        <nav class="main-nav">
            <div class="nav-icon-container nav-icon-container-not-clicked">
                <img class="nav-icon" src="/content/doublen987-logo-5.svg" />
            </div>
            <ul class="nav-items">
                <li class="nav-item">
                    <a href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a href="/blog/">Blog</a>
                </li>
                <li class="nav-item">
                    <a href="/projects/">Projects</a>
                </li>
                <li class="nav-item nav-item-left">
                    <a href="https://github.com/doublen987" target="_blank">
                    <svg id="github-link" xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
                    </a>
                </li>
                <li class="nav-item nav-item-left">
                    <a href="https://www.linkedin.com/in/nikola-nesovic-24214219a/" target="_blank">
                    <svg id="linkedin-link" xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 24 24"><path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"/></svg>
                    </a>
                </li>
                <li class="nav-item nav-item-left">
                    <a href="mailto:doublen987@gmail.com" target="_blank">
                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 24 24"><path d="M12.042 23.648c-7.813 0-12.042-4.876-12.042-11.171 0-6.727 4.762-12.125 13.276-12.125 6.214 0 10.724 4.038 10.724 9.601 0 8.712-10.33 11.012-9.812 6.042-.71 1.108-1.854 2.354-4.053 2.354-2.516 0-4.08-1.842-4.08-4.807 0-4.444 2.921-8.199 6.379-8.199 1.659 0 2.8.876 3.277 2.221l.464-1.632h2.338c-.244.832-2.321 8.527-2.321 8.527-.648 2.666 1.35 2.713 3.122 1.297 3.329-2.58 3.501-9.327-.998-12.141-4.821-2.891-15.795-1.102-15.795 8.693 0 5.611 3.95 9.381 9.829 9.381 3.436 0 5.542-.93 7.295-1.948l1.177 1.698c-1.711.966-4.461 2.209-8.78 2.209zm-2.344-14.305c-.715 1.34-1.177 3.076-1.177 4.424 0 3.61 3.522 3.633 5.252.239.712-1.394 1.171-3.171 1.171-4.529 0-2.917-3.495-3.434-5.246-.134z"/></svg>
                    </a>
                </li>
            </ul>
            <div id="modal" class="modal-hidden">
                <div class="modal-nav-item">
                    <a href="/">Home</a>
                </div>
                <div class="modal-nav-item">
                    <a href="/blog/">Blog</a>
                </div>
                <div class="modal-nav-item">
                    <a href="/projects/">Projects</a>
                </div>
                <div class="modal-nav-item">
                    <div class="modal-social">
                        <a href="https://github.com/doublen987" target="_blank">
                        <svg id="github-link" xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
                    </a>
                    </div>
                    <div class="modal-social">
                        <a href="https://www.linkedin.com/in/nikola-nesovic-24214219a/" target="_blank">
                        <svg id="linkedin-link" xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 24 24"><path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"/></svg>
                    </a>
                    </div>
                    <div class="modal-social">
                        <a href="mailto:doublen987@gmail.com" target="_blank">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 24 24"><path d="M12.042 23.648c-7.813 0-12.042-4.876-12.042-11.171 0-6.727 4.762-12.125 13.276-12.125 6.214 0 10.724 4.038 10.724 9.601 0 8.712-10.33 11.012-9.812 6.042-.71 1.108-1.854 2.354-4.053 2.354-2.516 0-4.08-1.842-4.08-4.807 0-4.444 2.921-8.199 6.379-8.199 1.659 0 2.8.876 3.277 2.221l.464-1.632h2.338c-.244.832-2.321 8.527-2.321 8.527-.648 2.666 1.35 2.713 3.122 1.297 3.329-2.58 3.501-9.327-.998-12.141-4.821-2.891-15.795-1.102-15.795 8.693 0 5.611 3.95 9.381 9.829 9.381 3.436 0 5.542-.93 7.295-1.948l1.177 1.698c-1.711.966-4.461 2.209-8.78 2.209zm-2.344-14.305c-.715 1.34-1.177 3.076-1.177 4.424 0 3.61 3.522 3.633 5.252.239.712-1.394 1.171-3.171 1.171-4.529 0-2.917-3.495-3.434-5.246-.134z"/></svg>
                    </a>
                    </div>
                </div>
                
            </div>
        </nav>
    </header>
    <main>
        `)
	_buffer.WriteString(`
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="/content/js/he.js"></script>
    <script src="/content/js/edittag.js"></script>

    <div class="editor-container">
        <form id="form1" action="/tag/edit" enctype="multipart/form-data" method="POST">
            <div class="input-container">
                <label for="SelectedTag" class="editor-label">Choose a post:</label>
                <select name="SelectedTag" id="chosen-tag" class="editor-select">
                    <option value="None">New tag</option>
                    `)
	for _, tag := range tags {
		_buffer.WriteString(`
                        <option value="`)
		hero.EscapeHTML(tag.ID, _buffer)
		_buffer.WriteString(`">`)
		hero.EscapeHTML(tag.Name, _buffer)
		_buffer.WriteString(`</option>
                        
                    `)
	}
	_buffer.WriteString(`
                </select>
                `)
	for _, tag := range tags {
		_buffer.WriteString(`
                    <div id="name-`)
		hero.EscapeHTML(tag.ID, _buffer)
		_buffer.WriteString(`" style="display:none;">`)
		hero.EscapeHTML(tag.Name, _buffer)
		_buffer.WriteString(`</div>
                    <div id="description-`)
		hero.EscapeHTML(tag.ID, _buffer)
		_buffer.WriteString(`" style="display:none;">`)
		hero.EscapeHTML(tag.Description, _buffer)
		_buffer.WriteString(`</div>
                    <div id="content-`)
		hero.EscapeHTML(tag.ID, _buffer)
		_buffer.WriteString(`" style="display:none;">`)
		hero.EscapeHTML(tag.Content, _buffer)
		_buffer.WriteString(`</div>
                    <div id="thumbnail-`)
		hero.EscapeHTML(tag.ID, _buffer)
		_buffer.WriteString(`" style="display:none;">`)
		hero.EscapeHTML(tag.Thumbnail, _buffer)
		_buffer.WriteString(`</div>
                    <div id="thumbnailstretched-`)
		hero.EscapeHTML(tag.ID, _buffer)
		_buffer.WriteString(`" style="display:none;">`)
		hero.FormatBool(tag.ThumbnailStretched, _buffer)
		_buffer.WriteString(`</div>
                `)
	}
	_buffer.WriteString(`
            </div>
            <div class="input-container">
                <label for="tag-name" class="editor-label">Name: </label>
                <input name="Name" id="tag-name" class="editor-input"></input>
            </div>
            <div class="input-container">
                <label for="tag-description" class="editor-label">Description: </label>
                <input name="Description" id="tag-description" class="editor-input"></input>
            </div>
            <div class="input-container">
                <label for="tag-thumbnail" class="editor-label">Thumbnail: </label>
                <input name="Thumbnail" type="file" accept="image/*" id="tag-thumbnail"></input>
            </div>
            <div class="label-container">
                <div class="editor-label">Thumbnail stretched: </div>
                <select name="ThumbnailStretched" id="tag-thumbnailstretched" class="text" >
                    <option id="tag-thumbnailstretched-option-true" value="true">True</option>
                    <option id="tag-thumbnailstretched-option-false" value="false">False</option>
                </select>
            </div>
            <div class="input-container">
                <img id="tag-thumbnail-image" src="/content/no-image.png">
            </div>
            <input type="hidden" id="tag-thumbnail-name" name="ThumbnailName" value="">
            <div class="submit-container">
                <button class="submit-btn" type="submit" name="Send" value="POST">Post</button>
                <button class="submit-btn" type="submit" name="Send" value="DELETE">Delete</button>
            </div>
        </form>
    </div>

    <script>
     
        initTagEditor()

    </script>
    
`)

	_buffer.WriteString(`
    </main>
    <footer>
        
    </footer>
    <script>
        initMobileMenu();
    </script>
</body>
</html>`)
	w.Write(_buffer.Bytes())

}
